### ISSUE TITLE
Puppeteer has error

### ISSUE THREAD

**Issue by ABatenev** [Flayms/Markdown2Pdf#90]
In 50% i have `PuppeteerSharp.NavigationException: 'Timeout of 30000 ms exceeded' ` when call await converter.Convert()

PuppeteerSharp.NavigationException
  HResult=0x80131500
  Message=Timeout of 30000 ms exceeded
  Source=PuppeteerSharp
  StackTrace:
   at PuppeteerSharp.Cdp.CdpFrame.<GoToAsync>d__17.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Markdown2Pdf.Markdown2PdfConverter.<_GeneratePdfAsync>d__50.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Markdown2Pdf.Markdown2PdfConverter.<_ConvertInternal>d__47.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Markdown2Pdf.Markdown2PdfConverter.<_Convert>d__46.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Markdown2Pdf.Markdown2PdfConverter.<Convert>d__43.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
TimeoutException: Timeout of 30000 ms exceeded

**Comment by Flayms** [comment]
Interesting, is it related to a new version?
And are you using very big markdown files? It might be Highlight.js taking too long, hitting the default timeouts from Puppeteer

**Comment by ABatenev** [comment]
I use the same md file, but in half of the cases the timeout causes an error, in the other it does not. This happens even for a single-line md file. Floating bug, I can't figure out why it's happening

**Comment by ABatenev** [comment]
Perhaps I have found a solution to this problem. On my VM, Chrome.exe does not close after an error, causing subsequent runs without closing the process to return a timeout error. Maybe you should add browser.Process.Close(); in the catch block when chrome starts?
https://github.com/hardkoded/puppeteer-sharp/issues/2393
![image](https://github.com/Flayms/Markdown2Pdf/assets/91783410/e875696f-4579-489e-89e5-dfc77b73c9fb)

**Comment by Flayms** [comment]
Using `browser.Process.Close();` is keeping the Process stuck for me. In [#90](https://github.com/Flayms/Markdown2Pdf/tree/90-puppeteer-has-error) I changed to `await using` for the browser and page. Can you check if this resolves the issue?

**Comment by INOPIAE** [comment]
I run in the timeout if my CPU is busy with other workloads.
